# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Joey Nichols | Web Developer
email: joeyquarters@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio and blog for Washington, D.C. based Web Developer, Joey Nichols
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.joeyquarters.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: joeyquarters
github_username:  joeyquarters
google_analytics: UA-89926811-1

# Markdown settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

# SCSS Settings
sass:
  add_charset: true
  sass_dir: assets/scss
  style: compressed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - README.md
  - assets/scss

# Plugin settings
gems:
  - jekyll-feed
  - jekyll-sitemap